# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='particioants')),
            ],
            options={
                'db_table': 'dialog',
            },
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='message_dialog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='forum.Dialog'),
            preserve_default=False,
        ),
    ]
