# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20171211_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='message_from',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='message_to',
        ),
        migrations.AddField(
            model_name='dialog',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pm_dialog_recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialog',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pm_dialog_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialog',
            name='subject',
            field=models.CharField(default=1, max_length=255, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='message_sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
