# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_auto_20171212_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='message_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='message_date',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='message_dialog',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='message_sender',
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='dialog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Dialog', to='forum.Dialog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dialog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
