# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_auto_20171229_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='dialog',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pm_recipient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
