# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_topic_topic_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_pic',
            field=models.ImageField(default='static/img/default_topic_pic.jpeg', upload_to=''),
        ),
    ]
