# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_topic_topic_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_pic',
            field=models.ImageField(default='img/default_topic_pic.png', height_field='height', upload_to='', width_field='width'),
        ),
    ]
