# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20180120_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_included', models.IntegerField(default=0)),
                ('category_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_pic',
            field=models.ImageField(default='default_topic_pic.png', height_field='height', upload_to=forum.models.upload_location, width_field='width'),
        ),
    ]
